# Generated by Django 5.2 on 2025-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=50)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("Albea", "Albea"),
                            ("Alfa Romeo", "Alfa Romeo"),
                            ("Audi", "Audi"),
                            ("BMW", "BMW"),
                            ("Chevrolet", "Chevrolet"),
                            ("Citroen", "Citroen"),
                            ("Opel", "Opel"),
                            ("Renault", "Renault"),
                            ("Dacia", "Dacia"),
                            ("Fiat", "Fiat"),
                            ("Ford", "Ford"),
                            ("Volkswagen", "Volkswagen"),
                            ("Honda", "Honda"),
                            ("Hyundai", "Hyundai"),
                            ("Jeep", "Jeep"),
                            ("Kia", "Kia"),
                            ("Mazda", "Mazda"),
                            ("Mercedes", "Mercedes"),
                            ("Mini", "Mini"),
                            ("Mitsubishi", "Mitsubishi"),
                            ("Nissan", "Nissan"),
                            ("Peugeot", "Peugeot"),
                            ("Porsche", "Porsche"),
                            ("Range Rover", "Range Rover"),
                            ("Seat", "Seat"),
                            ("Skoda", "Skoda"),
                            ("Subaru", "Subaru"),
                            ("Toyota", "Toyota"),
                            ("Isuzu", "Isuzu"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("is_popular", models.BooleanField(default=False)),
            ],
        ),
    ]
